include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    sort_pub_dependencies: ignore
    todo: info

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"